/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAccordion: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordion']
    BAccordionItem: typeof import('bootstrap-vue-next/components/BAccordion')['BAccordionItem']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    Eidolon: typeof import('./src/components/Eidolon.vue')['default']
    EidolonList: typeof import('./src/components/EidolonList.vue')['default']
    EidolonListHeader: typeof import('./src/components/EidolonListHeader.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    ItemGroup: typeof import('./src/components/ItemGroup.vue')['default']
    ItemList: typeof import('./src/components/ItemList.vue')['default']
    ItemRow: typeof import('./src/components/ItemRow.vue')['default']
    StarLevel: typeof import('./src/components/StarLevel.vue')['default']
  }
}
